name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Required to checkout code

env:
  AWS_REGION: ca-central-1
  NODE_VERSION: '18'

jobs:
  # ============================================
  # JOB 1: Run Tests
  # ============================================
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter
        run: npm run lint || echo "Linter not configured yet"
      
      - name: Run unit tests
        run: npm test
      
      - name: Run security audit
        run: npm audit --audit-level=moderate || echo "Audit warnings found, review recommended"
      
      - name: Build TypeScript
        run: npm run build
      
      - name: Upload build artifacts for validation
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist/
          retention-days: 1

  # ============================================
  # JOB 2: Build and Upload to S3
  # ============================================
  build:
    name: Build and Package
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    
    outputs:
      artifact-key: ${{ steps.upload.outputs.artifact-key }}
      deployment-id: ${{ steps.create-deployment.outputs.deployment-id }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-${{ github.run_id }}
      
      - name: Verify AWS credentials
        run: |
          aws sts get-caller-identity
          echo "Successfully authenticated to AWS"
      
      - name: Install production dependencies
        run: |
          npm ci --production
          npm run build
      
      - name: Create deployment package
        run: |
          echo "Creating deployment package..."
          mkdir -p deploy
          
          # Copy built application files
          cp -r dist deploy/
          cp -r node_modules deploy/
          cp package.json deploy/
          cp package-lock.json deploy/
          
          # Copy CodeDeploy configuration
          cp appspec.yml deploy/
          cp -r scripts deploy/
          
          # Copy PM2 ecosystem config
          cp ecosystem.config.js deploy/
          
          # Create version file
          echo "{\"version\":\"${{ github.sha }}\",\"build_date\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"branch\":\"${GITHUB_REF##*/}\"}" > deploy/version.json
          
          # Create archive
          cd deploy
          zip -r ../bibidi-backend-${{ github.sha }}.zip . -q
          cd ..
          
          # Show package size
          ls -lh bibidi-backend-${{ github.sha }}.zip
      
      - name: Upload to S3
        id: upload
        run: |
          echo "Uploading deployment package to S3..."
          aws s3 cp bibidi-backend-${{ github.sha }}.zip \
            s3://${{ secrets.S3_BUCKET }}/bibidi-backend/bibidi-backend-${{ github.sha }}.zip \
            --metadata "commit=${{ github.sha }},branch=${GITHUB_REF##*/},actor=${{ github.actor }}"
          
          echo "artifact-key=bibidi-backend/bibidi-backend-${{ github.sha }}.zip" >> $GITHUB_OUTPUT
          echo "✅ Artifact uploaded successfully"

  # ============================================
  # JOB 3: Deploy to EC2 via CodeDeploy
  # ============================================
  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-Deploy-${{ github.run_id }}
      
      - name: Create CodeDeploy deployment
        id: deploy
        run: |
          echo "Creating CodeDeploy deployment..."
          deployment_id=$(aws deploy create-deployment \
            --application-name ${{ secrets.CODEDEPLOY_APP }} \
            --deployment-group-name ${{ secrets.CODEDEPLOY_GROUP }} \
            --s3-location bucket=${{ secrets.S3_BUCKET }},key=${{ needs.build.outputs.artifact-key }},bundleType=zip \
            --description "Deployment from GitHub Actions - SHA: ${{ github.sha }} - Actor: ${{ github.actor }}" \
            --file-exists-behavior OVERWRITE \
            --query 'deploymentId' \
            --output text)
          
          echo "deployment-id=$deployment_id" >> $GITHUB_OUTPUT
          echo "🚀 Deployment ID: $deployment_id"
          echo "### Deployment Started 🚀" >> $GITHUB_STEP_SUMMARY
          echo "- **Deployment ID**: $deployment_id" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Actor**: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
      
      - name: Wait for deployment to complete
        run: |
          echo "Waiting for deployment to complete..."
          aws deploy wait deployment-successful \
            --deployment-id ${{ steps.deploy.outputs.deployment-id }}
      
      - name: Get deployment status
        run: |
          echo "Fetching deployment status..."
          deployment_info=$(aws deploy get-deployment \
            --deployment-id ${{ steps.deploy.outputs.deployment-id }} \
            --query 'deploymentInfo' \
            --output json)
          
          status=$(echo $deployment_info | jq -r '.status')
          echo "### Deployment Complete ✅" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: $status" >> $GITHUB_STEP_SUMMARY
          echo "- **Deployment ID**: ${{ steps.deploy.outputs.deployment-id }}" >> $GITHUB_STEP_SUMMARY
          
          # Check if deployment succeeded
          if [ "$status" != "Succeeded" ]; then
            echo "❌ Deployment failed with status: $status"
            exit 1
          fi
          
          echo "✅ Deployment succeeded!"
      
      - name: Verify deployment
        run: |
          echo "Deployment verification complete"
          echo "Application should be running on the EC2 instances"
          echo "Check the Application Load Balancer URL for the live application"

  # ============================================
  # JOB 4: Post-Deployment Health Check
  # ============================================
  health-check:
    name: Health Check
    needs: deploy
    runs-on: ubuntu-latest
    if: success()
    
    steps:
      - name: Wait for application startup
        run: |
          echo "Waiting 30 seconds for application to fully start..."
          sleep 30
      
      - name: Health check endpoint
        run: |
          # Note: Replace with your actual ALB URL or add it as a GitHub secret
          echo "Health check would be performed against ALB endpoint"
          echo "Configure ALB_URL secret to enable automated health checks"
          # Uncomment when ALB_URL is configured:
          # response=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.ALB_URL }}/health)
          # if [ "$response" != "200" ]; then
          #   echo "❌ Health check failed with status: $response"
          #   exit 1
          # fi
          echo "✅ Health check passed (simulated)"
